### GET request to example server
POST http://localhost:4000/Patient/add-patient
Content-Type: application/json

{
  "name": "prabakar1",
  "address": "Maderia, Portugal",
  "dateOfBirth": "1999-07-14",
  "email":"prabakar11@gmail.com",
  "registration": "2005-09-18"
}

###