### GET request to fetch all patients
#GET http://localhost:4000/Patient/get-patients
GET http://localhost:4004/api/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc2MTEwODY3NSwiZXhwIjoxNzYxMTEyMjc1fQ.w3fbut6pYcS6ByAF4eaSCUZJ0LkbBOXG_xq77ApbE14